id = "r85"
name = "r85"
version = "0.1.0"
schema_version = 1
description = "Based of 'Aquarelle Cymbidium' from <https://github.com/BeardedBear/bearded-theme>"
repository = "https://github.com/rgk85/zed-r85-themes"
authors = ["r85 <https://github.com/rgk85>"]
themes = ["themes/base.json"]
